# Generated by Django 4.0.5 on 2022-06-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-time')], max_length=50, null=True),
        ),
    ]
