# Generated by Django 4.0.5 on 2022-06-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-Time', 'Full-time'), ('Part-Time', 'Part-Time')], max_length=50, null=True),
        ),
    ]
